### ISSUE TITLE
ошибка сразу после установки и npm run dev

### ISSUE THREAD

**Issue by Nightwelf** [dulin666/vue-seed#8]
# ошибка:
`app.js:1598 Uncaught SyntaxError: Invalid or unexpected token`

# код с ошибкой:

```
/***/ }),
/* 139 */
/***/ (function(module, exports) {

eval("module.exports = function(module) {\r\n\tif(!module.webpackPolyfill) {\r\n\t\tmodule.deprecate = function() {};\r\n\t\tmodule.paths = [];\r\n\t\t// module.parent = undefined by default\r\n\t\tif(!module.children) module.children = [];\r\n\t\tObject.defineProperty(module, \"loaded\", {\r\n\t\t\tenumerable: true,\r\n\t\t\tget: function() {\r\n\t\t\t\treturn module.l;\r\n\t\t\t}\r\n\t\t});\r\n\t\tObject.defineProperty(module, \"id\", {\r\n\t\t\tenumerable: true,\r\n\t\t\tget: function() {\r\n\t\t\t\treturn module.i;\r\n\t\t\t}\r\n\t\t});\r\n\t\tmodule.webpackPolyfill = 1;\r\n\t}\r\n\treturn module;\r\n};\r\n\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiMTM5LmpzIiwic291cmNlcyI6WyJ3ZWJwYWNrOi8vLyh3ZWJwYWNrKS9idWlsZGluL21vZHVsZS5qcz9jM2MyIl0sInNvdXJjZXNDb250ZW50IjpbIm1vZHVsZS5leHBvcnRzID0gZnVuY3Rpb24obW9kdWxlKSB7XHJcblx0aWYoIW1vZHVsZS53ZWJwYWNrUG9seWZpbGwpIHtcclxuXHRcdG1vZHVsZS5kZXByZWNhdGUgPSBmdW5jdGlvbigpIHt9O1xyXG5cdFx0bW9kdWxlLnBhdGhzID0gW107XHJcblx0XHQvLyBtb2R1bGUucGFyZW50ID0gdW5kZWZpbmVkIGJ5IGRlZmF1bHRcclxuXHRcdGlmKCFtb2R1bGUuY2hpbGRyZW4pIG1vZHVsZS5jaGlsZHJlbiA9IFtdO1xyXG5cdFx0T2JqZWN0LmRlZmluZVByb3BlcnR5KG1vZHVsZSwgXCJsb2FkZWRcIiwge1xyXG5cdFx0XHRlbnVtZXJhYmxlOiB0cnVlLFxyXG5cdFx0XHRnZXQ6IGZ1bmN0aW9uKCkge1xyXG5cdFx0XHRcdHJldHVybiBtb2R1bGUubDtcclxuXHRcdFx0fVxyXG5cdFx0fSk7XHJcblx0XHRPYmplY3QuZGVmaW5lUHJvcGVydHkobW9kdWxlLCBcImlkXCIsIHtcclxuXHRcdFx0ZW51bWVyYWJsZTogdHJ1ZSxcclxuXHRcdFx0Z2V0OiBmdW5jdGlvbigpIHtcclxuXHRcdFx0XHRyZXR1cm4gbW9kdWxlLmk7XHJcblx0XHRcdH1cclxuXHRcdH0pO1xyXG5cdFx0bW9kdWxlLndlYnBhY2tQb2x5Zmls
```

**Comment by Nightwelf** [comment]
# результаты тестов:
`<скрыто> <скрытый путь>
> npm run unit

> vue-seed@1.0.0 unit <скрытый путь>
> cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run

(node:4460) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: d42067b2ff8a79695eb0
Version: webpack 2.3.1
Time: 7605ms
   Asset     Size  Chunks                    Chunk Names
index.js  1.64 MB       0  [emitted]  [big]  index.js
chunk    {0} index.js (index.js) 609 kB [entry] [rendered]
    [9] ./src/containers/about/about.js 1.56 kB {0} [optional] [built]
   [10] ./src/containers/home/home.js 3.14 kB {0} [optional] [built]
   [11] ./src/containers/notFound/notFound.js 1.58 kB {0} [optional] [built]
   [12] ./src/containers/project/project.js 736 bytes {0} [optional] [built]
   [13] ./src/containers/projects/projects.js 2.43 kB {0} [optional] [built]
   [14] ./src/store/types.js 1.16 kB {0} [built]
   [43] ./~/function-bind/index.js 111 bytes {0} [built]
   [44] ./src ^\.\/(?!main(\.js)?$) 1.58 kB {0} [built]
   [45] ./test/unit/specs \.spec$ 177 bytes {0} [built]
   [64] ./test/unit/index.js 272 bytes {0} [built]
  [139] ./src/components/projectsList/projectsList.css 981 bytes {0} [optional] [built]
  [140] ./src/components/welcome/welcome.css 966 bytes {0} [optional] [built]
  [141] ./src/containers/about/about.css 960 bytes {0} [optional] [built]
  [142] ./src/containers/home/home.css 957 bytes {0} [optional] [built]
  [143] ./src/containers/notFound/notFound.css 969 bytes {0} [optional] [built]
     + 133 hidden modules

ERROR in ./test/unit/specs/Hello.spec.js
Module not found: Error: Can't resolve 'src/components/Hello' in '<скрытый путь>\test\unit\specs'
 @ ./test/unit/specs/Hello.spec.js 2:0-41
 @ ./test/unit/specs \.spec$
 @ ./test/unit/index.js
23 03 2017 01:12:08.667:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
23 03 2017 01:12:08.682:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
23 03 2017 01:12:08.748:INFO [launcher]: Starting browser PhantomJS
23 03 2017 01:12:12.588:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket YzlkZPetS4ZwKQoiAAAA with id 51337180
23 03 2017 01:12:12.888:WARN [reporter]: SourceMap position not found for trace: undefined
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Error: Cannot find module "src/components/Hello"
  at index.js:13840

PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.3 secs / 0 secs)


PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
INFO LOG: 'You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html'

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "unit"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vue-seed@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-seed@1.0.0 unit script 'cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     <скрытый путь>\npm-debug.log

<скрыто> <скрытый путь>
> npm run e2e

> vue-seed@1.0.0 e2e <скрытый путь>
> node test/e2e/runner.js

Starting selenium server... (node:16412) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
started - PID:  16252

[Test] Test Suite
=====================

Running:  default e2e tests
> Listening at http://localhost:8080

 √ Element <#app> was visible after 188 milliseconds.
 × Testing if element <.hello> is present.  - expected "present" but got: "not present"
    at Object.defaultE2eTests [as default e2e tests] (<скрытый путь>/test/e2e/specs/test.js:14:15)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)


FAILED:  1 assertions failed and 1 passed (12.881s)

 _________________________________________________

 TEST FAILURE:  1 assertions failed, 1 passed. (13.551s)

 × test

   - default e2e tests (12.881s)
   Testing if element <.hello> is present.  - expected "present" but got: "not present"
       at Object.defaultE2eTests [as default e2e tests] (<скрытый путь>/test/e2e/specs/test.js:14:15)
       at _combinedTickCallback (internal/process/next_tick.js:67:7)


npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! vue-seed@1.0.0 e2e: `node test/e2e/runner.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-seed@1.0.0 e2e script 'node test/e2e/runner.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node test/e2e/runner.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     <скрытый путь>\npm-debug.log

<скрыто> <скрытый путь>`

**Comment by dulin666** [comment]
Я извиняюсь за столь долгий ответ, на то были свои причины. Спасибо за обратную связь, доработал vue-seed с учетом вашего коментария. Сейчас все работает и я на стадии разработки нового проекта для быстрого старта.
